### ISSUE TITLE
Artifact not available: 'io.rainfall:rainfall-core:1.1.3-SNAPSHOT'

### ISSUE THREAD

**Issue by abelsromero** [aurbroszniowski/jbcn2016#1]
Hi,

I tried to build the project following the 'clean install' step but it fails because the 'rainfall-care:1.1.3-SNAPSHOT' artifact cannot be resolved.
Do we need to add some maven repository? or compile it locally?

Also noticed that the PerfTest class throws and exception that is not found.

**Comment by aurbroszniowski** [comment]
Hi, sorry about that, it was a missing repository declaration in the pom.I just fixed it, thank you for your feedback!

**Comment by abelsromero** [comment]
Happy to help :+1:
